### ISSUE TITLE
Packaging issues.

### ISSUE THREAD

**Issue by VarLad** [carp-lang/Carp#1428]
I was able to package Carp for Fedora, with a catch. 
Downloading ghc provided by stack errors on Fedora 36 (only). That'll get fixed as it gets updated, but I'd rather use the `ghc` version provided by Fedora. 
So I tried compiling Carp 0.5.5 with ghc 9.2.4, and I get this error
```
[11 of 53] Compiling Obj

/var/home/varlad/Carp-0.5.5/src/Obj.hs:1011:10: error:
    • No instance for (Eq Context)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Hashable Context’
     |
1011 | instance Hashable Context where
     |          ^^^^^^^^^^^^^^^^
Completed 16 action(s).

--  While building package CarpHask-0.5.5.0 (scroll up to its section to see the error) using:
      /home/username/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.6.3.0_ghc-9.2.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.6.3.0 build lib:CarpHask exe:carp exe:carp-header-parse --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

Here's my stack.yaml file
```yaml
resolver: ghc-9.2

packages:
- '.'

extra-deps: 
- ansi-terminal-0.11.3@sha256:cc499d5f4c09a7213cd752ee69dbb5a5b8f3d1c777274e609eea4bca5c68ac8c,3321
- blaze-html-0.9.1.2@sha256:74b89ffa665891f528f571ce9e3c2dce24f698563f14b6f5e9e0512eccdf5dc2,3062
- blaze-markup-0.8.2.8@sha256:8a47373003f472e851afbc3332bb9e0bf1b539a0dfad631bceb704332749c6c2,2293
- cmark-0.6@sha256:9b87382da228d729a0ac42489a02eab52ffff628f29a12436a34715a6b409d12,3792
- edit-distance-0.2.2.1@sha256:4d33a49cd383d50af090f1b888642d10116e43809f9da6023d9fc6f67d2656ee,2351
- hashable-1.4.1.0@sha256:50b2f002c68fe67730ee7a3cd8607486197dd99b084255005ad51ecd6970a41b,5019
- open-browser-0.2.1.0@sha256:e4be4a206f5ab6ddb5ae4fbb39101529196e20af5670c5d33326fea6eff886fd,1529
- optparse-applicative-0.17.0.0@sha256:0713e54cbb341e5cae979e2ac441eb3a5ff42e303001f432bd58c19e5638bdda,4967
- split-0.2.3.5@sha256:f472fa7019647cacac3267742a6f7ac0a5c816f9890e80e4b826cd937436de87,2646
- ansi-wl-pprint-0.6.9@sha256:212144ea0623b1170807a4162db05d87f26cf10b334aeadd0edb377aba06a1ce,2425
- blaze-builder-0.4.2.2@sha256:f0017df374c330de0ebe0eb15eae8c48427bddefa1d81a3cb31c0a4812ecdb08,3685
- colour-2.3.6@sha256:ebdcbf15023958838a527e381ab3c3b1e99ed12d1b25efeb7feaa4ad8c37664a,2378
- random-1.2.1.1@sha256:dea1f11e5569332dc6c8efaad1cb301016a5587b6754943a49f9de08ae0e56d9,6541
- transformers-compat-0.7.2@sha256:044fb9955f63ee138fcebedfdcbe54afe741f2d5892a2d0bdf3a8052bd342643,5601
- splitmix-0.1.0.4@sha256:804e2574bc7e32d08cbab91e47ee6287b4df7d50851d73f9e778f94a9a7814c7,6521

flags: {}
extra-package-dbs: []
system-ghc: true
```
